name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_nYfSJRw52ggAILhNurU3MidWvuxf/TrHYfhzuoo"